<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Blog\Module'                        => __DIR__ . '/Module.php',
    'Blog\Controller\ListController' => __DIR__ . '/src/Blog/Controller/ListController.php',
    'BlogTest\Framework\TestCase'        => __DIR__ . '/tests/Blog/Framework/TestCase.php',
    'BlogTest\SampleTest'                => __DIR__ . '/tests/Blog/SampleTest.php',
);
